normal_addons:
  metric_server:
    name: metric-server
    enable: "{{ enable_metallb }}"
    namespace: kube-system
    directories:
      - metric-server
    templates:
      - metric-server/metrics-server-sa.yml
      - metric-server/metrics-server-rbac.yml
      - metric-server/metrics-apiservice.yml
      - metric-server/metrics-server-pdb.yaml
      - metric-server/metrics-server-svc.yml
      - metric-server/metrics-server-dp.yml
    worker:
      - "{{ images.metrics_server.file }}"

  kuboard:
    name: kuboard
    enable: "{{ enable_kuboard }}"
    namespace: kube-system
    directories:
      - kuboard
    templates:
      - kuboard/kuboard.yaml
    worker:
      - "{{ images.kuboard.file }}"

  npd:
    name: npd
    enable: "{{ enable_npd }}"
    namespace: kube-system
    directories:
      - npd
    templates:
      - npd/npd-config.yaml
      - npd/npd-ds.yaml
    all:
      - "{{ images.npd.file }}"

  storage_nfs:
    name: storage-nfs
    enable: "{{ enable_storage_nfs }}"
    namespace: kube-system
    directories:
      - storage-nfs
    templates:
      - storage-nfs/nfs-client-provisioner.yaml
      - storage-nfs/storage-class.yaml
      - storage-nfs/test-nfs-storage-class.yaml
    worker:
      - "{{ images.nfs_client_provisioner.file }}"

  rbac_manager:
    name: rbac-manager
    enable: "{{ enable_rbac_manager }}"
    namespace: kube-system
    directories:
      - rbac-manager
    templates:
      - rbac-manager/rbac-manager.yml
    worker:
      - "{{ images.rbac_manager.file }}"

  kubectl_debug:
    name: kubectl-debug
    enable: "{{ enable_kubectl_debug }}"
    namespace: kube-system
    directories:
      - kubectl-debug
    templates:
      - kubectl-debug/kubectl-debug-agent.yaml
    all:
      - "{{ images.kubectl_debug.file }}"
      - "{{ images.netshoot.file }}"
