- block:
  - name: 创建 kubeadm-config 目录
    file: path={{ item }} state=directory
    with_items:
    - "{{ kubernetes_etc_dir }}/kubeadm-config"

  - name: master 节点渲染相关配置文件
    template:
      src="{{ item.src }}.j2"
      dest="{{ item.dest }}"
      owner="root"
      group="root"
      mode="0644"
    with_items:
      - { src: "master/kubeadm-config-cm.yaml", dest: "{{ kubernetes_etc_dir }}/kubeadm-config/kubeadm-config-cm.yaml" }
      - { src: "kubelet/kubelet-config-cm.yaml", dest: "{{ kubernetes_etc_dir }}/kubeadm-config/kubelet-config-cm.yaml" }
      - { src: "kube-proxy/kube-proxy-cm.yaml", dest: "{{ kubernetes_etc_dir }}/kubeadm-config/kube-proxy-cm.yaml" }

  - name: 配置 kubeadm-config
    shell: >
      {{ kubernetes_bin_dir }}/kubectl apply -f {{ kubernetes_etc_dir }}/kubeadm-config/
    when: "inventory_hostname == groups['masters'][0]"
  when: "inventory_hostname in (groups['masters'] + groups['add-masters'])"
