- include_tasks: master.yml
  when: inventory_hostname in (groups['masters'] + groups['add-masters'])
  register: setup_master

- include_tasks: approve/rbac.yml
  when: setup_master is succeeded
  register: rbac_result

# - include_tasks: kubeadm-config.yml
#   when: rbac_result is succeeded
#   register: kubeadm_result

- include_tasks: worker.yml
  # when: kubeadm_result is succeeded
  register: setup_all

# - name: 等待 kubectl 能操作集群
#   shell: >
#     {{ kubernetes_bin_dir }}/kubectl get cs
#   environment:
#       KUBECONFIG: "{{ kubernetes_etc_dir }}/admin.conf"
#   until: waiting_for_cluster.rc == 0 and waiting_for_cluster.stdout.find("Unhealthy") == -1
#   retries: 3
#   delay: "{{ retry_stagger }}"
#   changed_when: false
#   register: waiting_for_cluster
