apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-metallb-dpl
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-metallb
  template:
    metadata:
      labels:
        app: test-metallb
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - name: http
          containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: test-metallb-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-metallb
  type: LoadBalancer
  # externalTrafficPolicy: Local
