
########################################################
# 普通用户（devops）添加集群操作权限
########################################################

- hosts: "kube_cluster"
  tasks:
  - name: 判断执行用户是否存在
    action: shell /usr/bin/getent passwd {{ item }} | /usr/bin/wc -l | tr -d ''
    register: user_exist
    with_items:
    - devops

  - name: 添加非 root 用户 docker 命令执行目录环境变量
    when: 'item.stdout != "0"'
    lineinfile:
      dest: "/home/{{ item.item }}/.bash_profile"
      state: present
      regexp: "{{ docker_bin_dir }}"
      line: 'export PATH={{ docker_bin_dir }}:$PATH'
    with_items:
    - "{{ user_exist['results'] }}"

  - name: 添加非 root 用户 docker 命令权限
    when: 'item.stdout != "0"'
    shell: >
      usermod -aG docker {{ item.item }};
    with_items:
    - "{{ user_exist['results'] }}"

  - name: 添加非 root 用户 kubectl 命令执行目录环境变量
    when: 'item.stdout != "0"'
    lineinfile:
      dest: "/home/{{ item.item }}/.bash_profile"
      state: present
      regexp: "{{ kubernetes_bin_dir }}"
      line: 'export PATH={{ kubernetes_bin_dir }}:$PATH'
    with_items:
    - "{{ user_exist['results'] }}"

  - name: 添加非 root 用户 kubectl 命令自动补全
    when: 'item.stdout != "0"'
    lineinfile:
      dest: "/home/{{ item.item }}/.bashrc"
      state: present
      regexp: 'kubectl completion'
      line: 'source <(kubectl completion bash)'
    with_items:
    - "{{ user_exist['results'] }}"

  - name: 从 groups['masters'][0] 节点分发非 root 用户 kubeconfig 认证文件
    when: 'item.stdout != "0"'
    synchronize: src="{{ ansible_env.HOME }}/.kube/" dest="/home/{{ item.item }}/.kube/"
    with_items:
    - "{{ user_exist['results'] }}"
    delegate_to: "{{ groups['masters'][0] }}"

  - name: 添加非 root 用户 helm 命令执行目录环境变量
    when: 'item.stdout != "0"'
    lineinfile:
      dest: "/home/{{ item.item }}/.bash_profile"
      state: present
      regexp: "{{ helm2_bin_dir }}"
      line: 'export PATH={{ helm2_bin_dir }}:$PATH'
    with_items:
    - "{{ user_exist['results'] }}"

  - name: 添加非 root 用户 helm 命令 tls 权限
    when: 'item.stdout != "0"'
    lineinfile:
      dest: "/home/{{ item.item }}/.bashrc"
      state: present
      regexp: 'HELM_TLS_ENABLE=true'
      line: 'export HELM_TLS_ENABLE=true'
    with_items:
    - "{{ user_exist['results'] }}"

  - name: 添加非 root 用户 helm 命令自动补全
    when: 'item.stdout != "0"'
    lineinfile:
      dest: "/home/{{ item.item }}/.bashrc"
      state: present
      regexp: 'helm completion'
    with_items:
    - "{{ user_exist['results'] }}"

  - name: 从 groups['masters'][0] 节点分发非 root 用户 helm 认证文件
    when: 'item.stdout != "0"'
    synchronize: src="{{ ansible_env.HOME }}/.helm/" dest="/home/{{ item.item }}/.helm/"
    with_items:
    - "{{ user_exist['results'] }}"
    delegate_to: "{{ groups['masters'][0] }}"
