# Tear down nodes
- hosts: "{{ groups['masters'][0] }}"
  become: yes
  roles:
  - { role: cluster-path }
  - { role: cluster-default }
  - { role: cluster-ops/delete }

- hosts: delete_nodes
  become: yes
  roles:
  - { role: cluster-default }
  - { role: cluster-path }
  - { role: cluster-reset, reset_flannel: true }
  - { role: cluster-reset , reset_k8s: true }
  - { role: cluster-reset, reset_kernel_module: false }
