- hosts: kube_cluster
  become: true
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: cluster-reset, reset_kernel_module: false }

- hosts: kube_masters
  become: true
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: cluster-reset, reset_ha: true }

- hosts: kube_cluster
  become: true
  gather_facts: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: cluster-reset, reset_k8s: true }

- hosts: kube_etcds
  become: true
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
  - { role: cluster-reset, reset_etcd: true }
