- name: 确认 kube-scheduler 运行状态
  command: /bin/true
  notify:
    - 启动 kube-scheduler 服务，并设置开机启动
    - 以轮询的方式等待 kube-scheduler 服务启动完成
    - 检查 kube-scheduler 服务状态

- name: 启动 kube-scheduler 服务，并设置开机启动
  systemd:
    name: kube-scheduler
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_scheduler
  until: started_scheduler is succeeded
  retries: 3
  delay: "{{ retry_stagger }}"

- name: 以轮询的方式等待 kube-scheduler 服务启动完成
  when: started_scheduler is succeeded
  shell: "systemctl status kube-scheduler.service | grep Active"
  register: scheduler_status
  until: '"running" in scheduler_status.stdout'
  retries: 2
  delay: "{{ retry_stagger }}"

- name: 检查 kube-scheduler 服务状态
  when: scheduler_status is succeeded
  wait_for:
    host: "127.0.0.1"
    port: "{{ item }}"
    delay: 5
    connect_timeout: 60
    timeout: 300
  with_items:
    - "{{ scheduler.secure_port }}"
