
- name: 安装 haproxy
  package: name=haproxy state=present
  # async表示上述命令的等待时间, 设置为0时会一直等待命令结束
  async: 5
  # poll表示检查step操作结果的间隔时长,设置为0表示 不用等待结果,继续做下面的操作,我们可以在下面的step中来验证这个命令是否成功执行.
  poll: 0
  register: haproxy_result

- name: 创建 haproxy 配置目录
  file: name="{{ haproxy_etc_dir }}" state=directory

- name: 配置 haproxy systemd service 文件
  template:
    src: "haproxy.service.j2"
    dest: "{{ systemd_service_dir }}/haproxy.service"
    owner: root
    group: root
    mode: 0644

- name: 配置 haproxy
  template: src=haproxy.cfg.j2 dest="{{ haproxy_etc_dir }}/haproxy.cfg"
