- block:
  - include_tasks: haproxy.yml
  - include_tasks: keepalived.yml

  - name: 启动haproxy keepalived
    systemd:
      name: "{{ item }}"
      daemon_reload: yes
      state: restarted
      enabled: yes
    with_items:
      - keepalived
      - haproxy
  when: inventory_hostname in groups['kube_masters']
