- name: 创建 kubernetes 证书存放目录
  when: "inventory_hostname in groups['kube_cluster']"
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ k8s_pki_dir }}"

- name: 创建 etcd 证书存放目录
  when: "inventory_hostname in groups['kube_etcds']"
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ etcd_pki_dir }}"

- name: 安装 cfssl
  when: "binary_way is defined and binary_way.enable and binary_way.cfssl_cert"
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    state: present
    regexp: "{{ cfssl_bin_dir }}"
    line: export PATH="{{ cfssl_bin_dir }}:$PATH"
