- name: 当前会话加载 kubectl kubeadm 命令，并自动补全
  shell: >
    {{ kubernetes_bin_dir }}/{{ item }} completion bash > /etc/bash_completion.d/{{ item }};
    source {{ ansible_env.HOME }}/.bash_profile
  args:
    executable: /bin/bash
  with_items:
    - kubectl
    - kubeadm

- name: 二进制方式搭建 kubernetes 集群
  when: "binary_way is defined and binary_way.enable"
  include_tasks: binary.yml

- name: kubeadm 方式搭建 kubernetes 集群
  when: "kubeadm_way is defined and kubeadm_way.enable"
  include_tasks: kubeadm.yml
