---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "10.10.10.49:8443"
    token: 12zptv.qq7dsmro99em3m17
    unsafeSkipCAVerification: true
  timeout: 4m0s
  tlsBootstrapToken: 12zptv.qq7dsmro99em3m17
nodeRegistration:
  kubeletExtraArgs:
    network-plugin: cni
    root-dir: /var/lib/kubelet
    hostname-override: 10.10.10.5
    pod-infra-container-image: registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
  criSocket: /var/run/dockershim.sock
  name: 10.10.10.5
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# 身份验证
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
# 授权
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
# 监听地址
address: 0.0.0.0
# kubelet监听端口
port: 10250
# kubelet只读端口，用于指标数据采集
readOnlyPort: 10255
# kubelet健康检查端口
healthzBindAddress: 127.0.0.1
healthzPort: 10248
clusterDNS:
- "172.31.0.10"
clusterDomain: "cluster.local"
configMapAndSecretChangeDetectionStrategy: Watch
featureGates:
  CPUManager: true
  DevicePlugins: true
  RotateKubeletServerCertificate: true
  RotateKubeletClientCertificate: true
staticPodPath: "/etc/kubernetes/manifests"
staticPodURL: ""
failSwapOn: true
kubeletCgroups: "/podruntime.slice"
systemCgroups: ""
cgroupDriver: "systemd"
cgroupsPerQOS: true
cgroupRoot: /
containerLogMaxFiles: 10
containerLogMaxSize: 20Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuCFSQuotaPeriod: 100ms
cpuManagerPolicy: static
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enableContentionProfiling: true
enforceNodeAllocatable:
- pods
- kube-reserved
- system-reserved
eventBurst: 10
eventRecordQPS: 5
# 镜像删除策略
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
# Node 资源驱逐策略
evictionHard:
  imagefs.available: "15%"
  memory.available: "100Mi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
# kubelet 资源驱逐策略
kubeReserved:
  cpu: "100m"
  memory: "256M"
kubeReservedCgroup: "/podruntime.slice"
# 系统资源驱逐策略
systemReserved:
  cpu: "500m"
  memory: "1G"
  ephemeral-storage: "10G"
systemReservedCgroup: "/system.slice"
evictionSoft: {}
evictionPressureTransitionPeriod: 5m0s
fileCheckFrequency: 20s
hairpinMode: hairpin-veth
httpCheckFrequency: 20s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kubeAPIBurst: 2000
kubeAPIQPS: 1000
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 128
nodeLeaseDurationSeconds: 40
nodeStatusReportFrequency: 1m0s
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
protectKernelDefaults: false
registryBurst: 20
resolvConf: /etc/resolv.conf
registryPullQPS: 5
rotateCertificates: true
serverTLSBootstrap: true
runtimeRequestTimeout: 10m0s
serializeImagePulls: false
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
tlsCertFile: "/etc/kubernetes/pki/kubelet.crt"
tlsPrivateKeyFile: "/etc/kubernetes/pki/kubelet.key"
volumeStatsAggPeriod: 1m0s
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
healthzBindAddress: "127.0.0.1:10256"
metricsBindAddress: "0.0.0.0:10249"
clientConnection:
  acceptContentTypes: ""
  burst: 200
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: "/var/lib/kube-proxy/kubeconfig.conf"
  qps: 100
clusterCIDR: "172.30.0.0/16"
configSyncPeriod: 10m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
detectLocalMode: ""
enableProfiling: false
hostnameOverride: "10.10.10.5"
featureGates:
  ValidateProxyRedirects: true
mode: "ipvs"
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: []
  minSyncPeriod: 0s
  scheduler: "rr"
  # metalLB
  strictARP: true
  syncPeriod: 30s
  tcpFinTimeout: 5s
  tcpTimeout: 5s
  udpTimeout: 5s
nodePortAddresses: []
oomScoreAdj: -999
portRange: ""
udpIdleTimeout: 250ms
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""
