
- name: 判断 krew-v{{ krew_version }}.tar.gz 是否存在
  when: inventory_hostname == groups['masters'][0]
  stat: path="{{ krew_bin_dir }}/krew-v{{ krew_version }}.tar.gz"
  register: check_krew_file

- name: 从 deploy 节点同步 krew-v{{ krew_version }}.tar.gz 文件
  when:
    - inventory_hostname == groups['masters'][0]
    - not check_krew_file.stat.exists
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ cache_dir }}krew-v{{ krew_version }}.tar.gz", dest: "{{ krew_bin_dir }}/krew-v{{ krew_version }}.tar.gz" }

- name: 渲染 krew 配置文件
  template: src="krew/krew.yaml.j2" dest="{{ krew_bin_dir }}/krew.yaml"

- name: 判断 krew 是否安装
  stat: path="{{ ansible_env.HOME }}/.krew/bin"
  register: check_krew_installation

- debug: msg="安装 krew，可能需要一定时间。。"
- name: 安装 krew
  when: not check_krew_installation.stat.exists
  shell: >
    {{ krew_bin_dir }}/krew-linux_amd64 install --manifest={{ krew_bin_dir }}/krew.yaml --archive={{ krew_bin_dir }}/krew-v{{ krew_version }}.tar.gz;
    rm -f {{ ansible_env.HOME }}/krew.tar.gz;
    # {{ ansible_env.HOME }}/.krew/bin/kubectl-krew update;
    # {{ ansible_env.HOME }}/.krew/bin/kubectl-krew install ns;

- name: 配置 krew 环境变量
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    state: present
    regexp: "krew"
    line: export PATH="{{ ansible_env.HOME }}/.krew/bin:$PATH"
