- name: 创建 {{ out_item.key }} 安装目录
  when: out_item.value.install_dir != ""
  file: path="{{ out_item.value.install_dir }}" state=directory

- name: 拉取 {{ out_item.key }} 二进制文件
  when:
    - out_item.value.archive_dir == ""
    - normal_install is undefined or not normal_install
  copy:
    src: "{{ cache_dir + out_item.value.archive_dir }}/{{ out_item.value.file }}"
    dest: "{{ out_item.value.install_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ out_item.value.bin }}"

- name: 拉取 {{ out_item.key }} 二进制文件
  when:
    - out_item.value.archive_dir != ""
    - normal_install is undefined or not normal_install
  copy:
    src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item }}"
    dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ out_item.value.bin }}"

- name: 安装 {{ out_item.key }}
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    state: present
    regexp: "{{ out_item.value.install_dir }}"
    line: export PATH="{{ out_item.value.install_dir }}:$PATH"
