version: "3.8"
services:
  openldap-aio:
    image: osixia/openldap:1.4.0
    container_name: openldap-aio
    command: [--copy-service, --loglevel, debug]
    restart: always
    # read_only: true
    ports:
      - "1389:389"
      - "1636:636"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Kubernetes LDAP"
      LDAP_DOMAIN: "${DOMAIN}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASSWORD}"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "${LDAP_READONLY_USER_PASSWORD}"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.pem"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.pem"
      # LDAP_TLS_ENFORCE 一定设置为 false, 某些应用不支持tls通信方式
      # LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_ENFORCE: "false"
      # LDAP_TLS_CIPHER_SUITE: "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC:-VERS-SSL3.0:HIGH:+SSLv3:+TLSv1:MEDIUM:+SSLv2:@STRENGTH:+SHA:+MD5:!NULL"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      # 不要设置成 demand，这个选项可以理解成双向认证，也就是客户端连接ldap时也许要提供证书，也就是客户端也需要有自己的证书
      LDAP_TLS_VERIFY_CLIENT: "demand"
      # LDAP_TLS_VERIFY_CLIENT: "try"
      LDAP_REPLICATION: "false"
      LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=\"${LDAP_CONFIG_PASSWORD}\" searchbase=\"cn=config\" type=refreshAndPersist retry=\"60 +\" timeout=1 starttls=critical"
      LDAP_REPLICATION_DB_SYNCPROV: "binddn=\"cn=admin,${LDAP_BASE_DN}\" bindmethod=simple credentials=\"${LDAP_ADMIN_PASSWORD}\" searchbase=\"${LDAP_BASE_DN}\" type=refreshAndPersist interval=00:00:00:10 retry=\"60 +\" timeout=1 starttls=critical"
      # LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://${LDAP_DOMAIN}']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ./ldap-aio/data:/var/lib/ldap
      - ./ldap-aio/config:/etc/ldap/slapd.d
      - ./cert/ldap.pem:/container/service/slapd/assets/certs/ldap.pem
      - ./cert/ldap.key:/container/service/slapd/assets/certs/ldap.key
      - ./cert/ca.pem:/container/service/slapd/assets/certs/ca.pem
      - /etc/localtime:/etc/localtime:ro
    # important: same as hostname
    domainname: "${LDAP_DOMAIN}"
    hostname: "${LDAP_DOMAIN}"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          memory: 128M
    networks:
      - kuboard-aio

  phpldapadmin-aio:
    # image: osixia/phpldapadmin:latest
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin-aio
    command: [--copy-service, --loglevel, debug]
    # read_only: true
    restart: always
    ports:
      # - "80:80"
      - "7443:443"
    environment:
      # /var/www/phpldapadmin/config/config.php
      # openldap 中开启了LDAP_TLS_ENFORCE，tls 也必须为 true
      # json 格式错误会报错/var/www/phpldapadmin/config/config.php错误
      # PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'${LDAP_DOMAIN}': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,${LDAP_BASE_DN}', 'bind_pass': '${LDAP_ADMIN_PASSWORD}'}]}]}, '${LDAP_DOMAIN}']"
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'${LDAP_DOMAIN}': [{'server': [{'tls': True}]},{'login': [{'bind_id': 'cn=admin,${LDAP_BASE_DN}', 'bind_pass': '${LDAP_ADMIN_PASSWORD}'}]}]}, '${LDAP_DOMAIN}']"
      PHPLDAPADMIN_SERVER_ADMIN: "ansandy@foxmail.com"
      PHPLDAPADMIN_SERVER_PATH: "/phpldapadmin"
      PHPLDAPADMIN_HTTPS: "true"
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: "${DOMAIN}.pem"
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: "${DOMAIN}.key"
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "ca.pem"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "true"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "try"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_CRT_FILENAME: "ldap.pem"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_KEY_FILENAME: "ldap.key"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: "ca.pem"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
      PHPLDAPADMIN_SSL_HELPER_PREFIX: "phpldapadmin"
      LDAP_CLIENT_SSL_HELPER_PREFIX: "ldap"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 50M
    tty: true
    stdin_open: true
    volumes:
      # config
      # - ./config/my-env.yaml:/container/environment/01-custom/env.yaml
      # - ./config/config.php:/var/www/phpldapadmin/config/config.php
      # https
      - ./https/${DOMAIN}.pem:/container/service/phpldapadmin/assets/apache2/certs/${DOMAIN}.pem
      - ./https/${DOMAIN}.key:/container/service/phpldapadmin/assets/apache2/certs/${DOMAIN}.key
      - ./https/ca.pem:/container/service/phpldapadmin/assets/apache2/certs/ca.pem
      # tls
      - ./cert/ldap.pem:/container/service/ldap-client/assets/certs/ldap.pem
      - ./cert/ldap.key:/container/service/ldap-client/assets/certs/ldap.key
      - ./cert/ca.pem:/container/service/ldap-client/assets/certs/ca.pem
      - /etc/localtime:/etc/localtime:ro
    domainname: "admin.${DOMAIN}"
    hostname: "admin.${DOMAIN}"
    depends_on:
      - openldap-aio
    networks:
      - kuboard-aio

  kuboard-aio:
    image: swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard:v3
    container_name: kuboard-aio
    restart: always
    # read_only: true
    ports:
      - "20080:80"
      - "3443:443"
      - "20081:10081/tcp"
      - "20081:10081/udp"
    environment:
      KUBOARD_TLS_CERT: "/etc/certs/ssl/server.crt"
      KUBOARD_TLS_KEY: "/etc/certs/ssl/server.key"
      KUBOARD_LOGIN_TYPE: "ldap"
      KUBOARD_ENDPOINT: "https://${KUBOARD_DOMAIN}:3443"
      KUBOARD_AGENT_SERVER_UDP_PORT: "10081"
      KUBOARD_AGENT_SERVER_TCP_PORT: "10081"
      KUBOARD_ROOT_USER: "test@demo.com"
      LDAP_HOST: "${LDAP_DOMAIN}"
      LDAP_BIND_DN: "${LDAP_BIND_DN}"
      LDAP_BIND_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_FILTER: "(objectClass=posixAccount)"
      LDAP_ID_ATTRIBUTE: "uid"
      LDAP_USER_NAME_ATTRIBUTE: "uid"
      LDAP_EMAIL_ATTRIBUTE: "mail"
      LDAP_DISPLAY_NAME_ATTRIBUTE: "cn"
      LDAP_GROUP_SEARCH_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_GROUP_SEARCH_FILTER: "(objectClass=posixGroup)"
      LDAP_USER_MACHER_USER_ATTRIBUTE: "gidNumber"
      LDAP_USER_MACHER_GROUP_ATTRIBUTE: "gidNumber"
      LDAP_GROUP_NAME_ATTRIBUTE: "cn"
      LDAP_ROOT_CA: "/etc/certs/ldap/ca.pem"
    # extra_hosts:
    # - "${LDAP_DOMAIN}:10.177.140.16"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          memory: 128M
    volumes:
      - ./cert/server.crt:/etc/certs/ssl/server.crt
      - ./cert/server.key:/etc/certs/ssl/server.key
      - ./cert/ca.pem:/etc/certs/ldap/ca.pem
      - ./kuboard-data-aio:/data
    networks:
      - kuboard-aio

networks:
  kuboard-aio:
