# cgroup driver
cgroup_driver: systemd

cri_engine_cli: >-
  {%- if container_runtime == 'docker' -%}
  docker
  {%- elif container_runtime == 'containerd' -%}
  crictl
  {%- endif -%}

cri_socket: >-
  {%- if container_runtime == 'containerd' -%}
  /run/containerd/containerd.sock
  {%- else -%}
  /var/run/dockershim.sock
  {%- endif -%}

# 应用于容器式守护进程的内存不足（OOM）分数（默认值：0）
containerd_oom_score: -999
containerd_grpc_max_recv_message_size: 16777216
containerd_grpc_max_send_message_size: 16777216
# 日志输出等级
containerd_debug_level: "info"
containerd_metrics_address: ""
containerd_metrics_grpc_histogram: false
containerd_max_container_log_line_size: -1
containerd_default_runtime: "runc"
containerd_snapshotter: "overlayfs"
containerd_runtimes:
  - name: runc
    type: "io.containerd.runc.v2"
    engine: ""
    root: ""
    options:
      BinaryName: ""
      CriuImagePath: ""
      CriuPath: ""
      CriuWorkPath: ""
      IoGid: 0
      IoUid: 0
      NoNewKeyring: false
      NoPivotRoot: false
      Root: ""
      ShimCgroup: ""
      # containerd 是否使用 systemd 作为 cgroup 驱动程序
      SystemdCgroup: true
containerd_use_systemd_cgroup: "true"
# 配置 Dockerhub 国内镜像加速地址
containerd_registries:
  "docker.io": "https://registry-1.docker.io"
  "gcr.io": "https://gcr.mirrors.ustc.edu.cn"
  "k8s.gcr.io": "https://gcr.mirrors.ustc.edu.cn/google-containers/"
  "quay.io": "https://quay.mirrors.ustc.edu.cn"
containerd_extra_args: ""

# docker0 ip
bip: "192.168.100.1/24"
# 定义国内加速镜像地址
proxy_registries:
  - "https://8trm4p9x.mirror.aliyuncs.com"
  - "https://docker.mirrors.ustc.edu.cn"
insecure_registry_cidr:
  - "{{ vip_address.split('.')[:-1] | join('.') }}.0/24"

# docker日志相关
log_driver: "json-file"
level: "warn"
maxsize: "10m"
maxfile: 3
# 开启 docker daemon iptables 规则，如果要使用 docker 创建容器设置为 true
enable_dockerd_iptables: true
# 开启 Restful API
enable_remote_api: false
