# ustc epel 源
# epel_yum_repo: http://mirrors.aliyun.com/epel/7/$basearch
epel_yum_repo: http://mirrors.ustc.edu.cn/epel/7/$basearch

# 设定容器运行时，可选 docker 和 containerd
container_runtime: docker
cgroup_driver: systemd
# 开启 docker proxy，可访问gcr
docker_enable_proxy: false
# docker 本地仓库地址
local_image_repo:
  - harbor.reg.local

# 配置etcd集群域名
etcd_domain_name: k8s.etcd.local

# kubernetes证书过期时间（天）
certs_expired: 3650
# kubernetes根证书过期时间（天）
ca_certs_expired: 36500
# Kubernetes  高可用配置
apiserver_secure_port: 6443
# 有 openresty、nginx、haproxy、envoy 和 slb 可选，默认使用 openresty
lb_mode: "nginx"
lb_apiserver_ip: "{{ vip_address }}"
lb_secure_port: 8443
lb_healthcheck_port: 8081
single_api_url: "https://{{ groups['masters'][0] }}:{{ apiserver_secure_port }}"
lb_api_url: "https://{{ vip_address }}:{{ lb_secure_port }}"
api_url: "{%- if groups['kube_masters'] | length == 1 -%}{{ single_api_url }}{%- else -%}{{ lb_api_url }}{%- endif %}"

# keepalived 参数
vip_interface: "{{ iface }}"
# 区分多个instance的VRRP组播，同网段不能重复，取值在0-255之间
# 因项目已设置vrrp报文单播模式，所以这个ROUTER_ID 即便同网段里面有重复也没关系
virtual_router_id: "66"
keepalived_password: "e82LKdrj59D0tHU"

# haproxy监控绑定端口
# haproxy负载均衡算法，常见如下：
# "roundrobin": 基于服务器权重的轮询
# "leastconn": 基于服务器最小连接数
# "source": 基于请求源IP地址
# "uri": 基于请求的URI
lb_haproxy_balance_alg: "leastconn"

# haproxy监控绑定端口
lb_envoy_admin_address_port: 9090

# kubernetes各组件镜像仓库前缀，离线镜像包里的镜像是：registry.cn-hangzhou.aliyuncs.com/google_containers(k8s.gcr.io init时会报错)
# kube_image_repository: k8s.gcr.io
kube_image_repository: registry.cn-hangzhou.aliyuncs.com/google_containers
# kube_image_repository: registry.aliyuncs.com/k8sxio

# 集群参数
cluster_name: kubernetes
cluster_domain_name: "cluster.local"
# k8s 集群 master 节点证书配置，可以添加多个ip和域名（比如增加公网ip和域名）
kube_master_external_ip:
  - "8.8.8.8"
kube_master_external_domain:
  - "kubernetes.io"

# coredns 自动安装
local_dns_cache: "169.254.20.10"

# metallb
# 选一段与node节点相同网段的地址
# metallb_protocol: bgp
metallb_protocol: layer2

ingress_type: nginx_ingress

# storageclass
# nfs_server_path: "/mnt/k8s-nfs"
nfs_server_path: "/nfs/data"

# 普通用户，docker/kubectl/helm 准入管理，非 root 也可以使用kubectl docker helm命令
normal_user:
  - devops

# ansible 运行剧本时，某些任务会重试，设置重试间隔基础时间为5秒
retry_stagger: 5
