# ustc epel 源
# epel_yum_repo: http://mirrors.aliyun.com/epel/7/$basearch
epel_yum_repo: http://mirrors.ustc.edu.cn/epel/7/$basearch

# 设定容器运行时，可选 docker 和 containerd
container_runtime: docker
cgroup_driver: systemd
# 开启 docker proxy，可访问gcr
docker_enable_proxy: false
# docker 本地仓库地址
local_image_repo:
  - harbor.reg.local

# 配置etcd集群域名
etcd_domain_name: k8s.etcd.local

# kubernetes证书过期时间（天）
certs_expired: 3650
# kubernetes根证书过期时间（天）
ca_certs_expired: 36500
# Kubernetes  高可用配置
apiserver_secure_port: 6443
# 有 openresty、nginx、haproxy、envoy 和 slb 可选，默认使用 openresty
lb_mode: "haproxy"
lb_apiserver_ip: "{{ vip_address }}"
lb_secure_port: 8443
single_api_url: "https://{{ groups['masters'][0] }}:{{ apiserver_secure_port }}"
lb_api_url: "https://{{ vip_address }}:{{ lb_secure_port }}"
api_url: "{%- if (groups['masters'] + groups['add_masters']) | length == 1 -%}{{ single_api_url }}{%- else -%}{{ lb_api_url }}{%- endif %}"

# kubernetes各组件镜像仓库前缀，离线镜像包里的镜像是：registry.cn-hangzhou.aliyuncs.com/google_containers(k8s.gcr.io init时会报错)
# kube_image_repository: k8s.gcr.io
kube_image_repository: registry.cn-hangzhou.aliyuncs.com/google_containers
# kube_image_repository: registry.aliyuncs.com/k8sxio

# pod cidr
cluster_name: kubernetes
cluster_domain_name: "cluster.local"
# k8s 集群 master 节点证书配置，可以添加多个ip和域名（比如增加公网ip和域名）
kube_master_external_ip:
  - "8.8.8.8"
kube_master_external_domain:
  - "kubernetes.io"

# metallb
# 选一段与node节点相同网段的地址
# metallb_protocol: bgp
metallb_protocol: layer2

ingress_type: nginx_ingress

# storageclass
nfs_server_path: "/nfs/data"
nas_server: "xxxxxxxxxxx.cn-hangzhou.nas.aliyuncs.com"
nas_server_path: "/"

# 普通用户，docker/kubectl/helm 准入管理，非 root 也可以使用kubectl docker helm命令
normal_user:
  - devops

# ansible 运行剧本时，某些任务会重试，设置重试间隔基础时间为5秒
retry_stagger: 5
