# 4.19版内核之后将nf_conntrack_ipv4更名为nf_conntrack，kube-proxy 1.12版本不支持在4.19以上版本内核下开启ipvs,建议安装4.18版或者lts版内核
# 详情可以查看：https://github.com/kubernetes/kubernetes/issues/70304

## centos 系统
# centos_kernel_repo: "http://mirror.rc.usf.edu/compute_lock/elrepo/kernel/el7/x86_64/RPMS"
# centos_kernel_repo: "https://elrepo.org/linux/kernel/el7/x86_64/RPMS"
centos_kernel_repo: "http://mirror.rc.usf.edu/elrepo/kernel/el7/x86_64/RPMS"
# centos_kernel_repo: "http://files.saas.hand-china.com/kernel/centos"
centos_kernel_type: "ml"
# centos_kernel_type: "lt"
# 5.x的版本有问题，会导致宿主机的网络不可用，虚机都无法访问
# centos_kernel_version: "4.20.13"
centos_kernel_version: "5.10.15"
centos_kernel_rpm_files:
  - "kernel-{{ centos_kernel_type }}-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"
  - "kernel-{{ centos_kernel_type }}-devel-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"
  - "kernel-{{ centos_kernel_type }}-headers-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"
  - "kernel-{{ centos_kernel_type }}-tools-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"
  - "kernel-{{ centos_kernel_type }}-tools-libs-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"
  - "kernel-{{ centos_kernel_type }}-tools-libs-devel-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"
  - "perf-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"
  - "python-perf-{{ centos_kernel_version }}-1.el7.elrepo.x86_64.rpm"

## ubuntu/debian 系统
apt_kernel_repo: "https://kernel.ubuntu.com/~kernel-ppa/mainline"
apt_kernel_version: "4.20.17"
apt_kernel_linux_base: http://security.ubuntu.com/ubuntu/pool/main/l/linux-base/linux-base_4.5ubuntu1~16.04.1_all.deb
apt_kernel_deb_files:
  - "{{ apt_kernel_repo }}/v{{ apt_kernel_version }}/linux-headers-{{ apt_kernel_version }}-042017_{{ apt_kernel_version }}-042017.201903190933_all.deb"
  - "{{ apt_kernel_repo }}/v{{ apt_kernel_version }}/linux-modules-{{ apt_kernel_version }}-042017-generic_{{ apt_kernel_version }}-042017.201903190933_amd64.deb"
  - "{{ apt_kernel_repo }}/v{{ apt_kernel_version }}/linux-image-unsigned-{{ apt_kernel_version }}-042017-generic_{{ apt_kernel_version }}-042017.201903190933_amd64.deb"
