# 4.19版内核之后将nf_conntrack_ipv4更名为nf_conntrack，kube-proxy 1.12版本不支持在4.19以上版本内核下开启ipvs,建议安装4.18版或者lts版内核
# 详情可以查看：https://github.com/kubernetes/kubernetes/issues/70304

## centos 系统
centos_kernel_repo_name: >-
  {%- if enable_kernel_longterm is defined and enable_kernel_longterm -%}
  longterm-kernel
  {%- else -%}
  normal-kernel
  {%- endif -%}

# centos_kernel_repo: "https://elrepo.org/linux/kernel/el7/x86_64/RPMS"
centos_kernel_repo_url: >-
  {%- if enable_kernel_longterm is defined and enable_kernel_longterm -%}
  "https://copr-be.cloud.fedoraproject.org/results/kwizart/kernel-longterm-4.19/epel-7-x86_64/"
  {%- else -%}
  "http://mirror.rc.usf.edu/elrepo/kernel/el7/$basearch/"
  {%- endif -%}

# centos_kernel_type: "lt"
centos_kernel_type: >-
  {%- if enable_kernel_longterm is defined and enable_kernel_longterm -%}
  longterm
  {%- else -%}
  ml
  {%- endif -%}

centos_kernel_package: >-
  {%- if enable_kernel_longterm is defined and enable_kernel_longterm -%}
  {{ kernel_longterm_package }}
  {%- else -%}
  {{ kernel_normal_package }}
  {%- endif -%}
kernel_longterm_package:
  - kernel-{{ centos_kernel_type }}
  - kernel-{{ centos_kernel_type }}-core
  - kernel-{{ centos_kernel_type }}-cross-headers
  - kernel-{{ centos_kernel_type }}-devel
  # - kernel-{{ centos_kernel_type }}-headers
  - kernel-{{ centos_kernel_type }}-modules
  - kernel-{{ centos_kernel_type }}-modules-extra
kernel_normal_package:
  - "kernel-{{ centos_kernel_type }}"
  - "kernel-{{ centos_kernel_type }}-devel"
  - "kernel-{{ centos_kernel_type }}-tools"
  - "kernel-{{ centos_kernel_type }}-tools-libs"
  - "kernel-{{ centos_kernel_type }}-tools-libs-devel"
  - "perf-{{ centos_kernel_version }}"
  - "python-perf-{{ centos_kernel_version }}"
  # - "kernel-{{ centos_kernel_type }}-headers"

## ubuntu/debian 系统
apt_kernel_repo: "https://kernel.ubuntu.com/~kernel-ppa/mainline"
apt_kernel_version: "4.20.17"
apt_kernel_linux_base: http://security.ubuntu.com/ubuntu/pool/main/l/linux-base/linux-base_4.5ubuntu1~16.04.1_all.deb
apt_kernel_deb_files:
  - "{{ apt_kernel_repo }}/v{{ apt_kernel_version }}/linux-headers-{{ apt_kernel_version }}-042017_{{ apt_kernel_version }}-042017.201903190933_all.deb"
  - "{{ apt_kernel_repo }}/v{{ apt_kernel_version }}/linux-modules-{{ apt_kernel_version }}-042017-generic_{{ apt_kernel_version }}-042017.201903190933_amd64.deb"
  - "{{ apt_kernel_repo }}/v{{ apt_kernel_version }}/linux-image-unsigned-{{ apt_kernel_version }}-042017-generic_{{ apt_kernel_version }}-042017.201903190933_amd64.deb"
