config:
  cluster_name: "{{ cluster_name }}"
  contexts:
    master:
    - name: kubernetes-admin
      context: kubernetes-admin@kubernetes
      ca: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}ca.pem{% else %}ca.crt{%- endif -%}"
      cert: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}admin.pem{% else %}admin.crt{%- endif -%}"
      cert_key: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}admin-key.pem{% else %}admin.key{%- endif -%}"
      path: "{{ kubernetes_etc_dir }}/admin.conf"
    - name: system:kube-controller-manager
      context: system:kube-controller-manager@kubernetes
      ca: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}ca.pem{% else %}ca.crt{%- endif -%}"
      cert: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kube-controller-manager.pem{% else %}kube-controller-manager.crt{%- endif -%}"
      cert_key: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kube-controller-manager-key.pem{% else %}kube-controller-manager.key{%- endif -%}"
      path: "{{ kubernetes_etc_dir }}/controller-manager.conf"
    - name: system:kube-scheduler
      context: system:kube-scheduler@kubernetes
      ca: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}ca.pem{% else %}ca.crt{%- endif -%}"
      cert: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kube-scheduler.pem{% else %}kube-scheduler.crt{%- endif -%}"
      cert_key: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kube-scheduler-key.pem{% else %}kube-scheduler.key{%- endif -%}"
      path: "{{ kubernetes_etc_dir }}/scheduler.conf"
    all:
    - name: "{% if hostvars[inventory_hostname]['ansible_host'] is defined %}system:node:{{ hostvars[inventory_hostname].ansible_hostname }}{% else %}system:node:{{ hostvars[inventory_hostname]['ansible_' + iface].ipv4.address }}{% endif %}"
      context: "{% if hostvars[inventory_hostname]['ansible_host'] is defined %}system:node:{{ hostvars[inventory_hostname].ansible_hostname }}@kubernetes{% else %}system:node:{{ hostvars[inventory_hostname]['ansible_' + iface].ipv4.address }}@kubernetes{% endif %}"
      ca: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}ca.pem{% else %}ca.crt{%- endif -%}"
      cert: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kubelet.pem{% else %}kubelet.crt{%- endif -%}"
      cert_key: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kubelet-key.pem{% else %}kubelet.key{%- endif -%}"
      path: "{{ kubernetes_etc_dir }}/kubelet.conf"
    - name: "kube-proxy"
      context: "system:kube-proxy@kubernetes"
      ca: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}ca.pem{% else %}ca.crt{%- endif -%}"
      cert: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kube-proxy.pem{% else %}kube-proxy.crt{%- endif -%}"
      cert_key: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}kube-proxy-key.pem{% else %}kube-proxy.key{%- endif -%}"
      path: "{{ kube_proxy_data_dir }}/kubeconfig.conf"
    - name: tls-bootstrap-token-user
      context: "tls-bootstrap-token-user@kubernetes"
      ca: "{{ k8s_pki_dir }}/{%- if binary_way is defined and binary_way.enable and binary_way.cfssl_cert -%}ca.pem{% else %}ca.crt{%- endif -%}"
      token: true
      path: "{{ kubernetes_etc_dir }}/bootstrap-kubelet.conf"
