- name: 将节点设置为维护者模式
  command: >
    {{ kubernetes_bin_dir }}/kubectl drain {{ hostvars['' + item].inventory_hostname }} --ignore-daemonsets --force --delete-local-data
  with_items: "{{ groups['delete_nodes'] }}"
  register: set_drain
  delegate_to: "{{ groups['masters'][0] }}"
  until: set_drain.rc == 0
  retries: 10
  delay: "{{ retry_stagger }}"

- name: 将节点资源从kube-apiserver中删除
  command: >
    {{ kubernetes_bin_dir }}/kubectl delete node {{ hostvars['' + item].inventory_hostname }}
  with_items: "{{ groups['delete_nodes'] }}"
  register: delete_node
  delegate_to: "{{ groups['masters'][0] }}"
  until: delete_node.rc == 0
  retries: 10
  delay: "{{ retry_stagger }}"
