# 软件资源校验
- name: 校验节点操作系统
  assert:
    that: ansible_distribution in [ 'CentOS','OracleLinux','RedHat','Ubuntu','Debian' ]
    msg: "节点：{{ inventory_hostname }} {{ ansible_distribution }}操作系统不支持本脚本安装Kubernetes集群。"

- name: 校验节点 systemd 类型操作系统
  assert:
    that: ansible_service_mgr == "systemd"
    msg: "节点：{{ inventory_hostname }} 期望为systemd类型操作系统，实际获取：{{ ansible_service_mgr }}，安装需求校验不通过。"

- name: 获取当前内核版本
  shell: "uname -r"
  register: get_kernel_version

- name: 设置内核版本参数
  set_fact:
    set_fact_kernel_version: "{{ get_kernel_version.stdout.split('-')[0] }}"

- name: 校验节点系统内核
  when: 'container_network == "cilium"'
  assert:
    that: set_fact_kernel_version is version('4.8', '>=')
    msg: "节点：{{ inventory_hostname }} 系统内核版本小于4.8，当前内核版本是：{{ set_fact_kernel_version }}, cilium cni需要内核高于4.8，安装需求校验不通过。"

- name: 校验节点系统内核
  when: 'container_network != "cilium"'
  assert:
    that: set_fact_kernel_version is version('3.10', '>=')
    msg: "节点：{{ inventory_hostname }} 当前系统内核版本是：{{ set_fact_kernel_version }}, 内核版本过低，请先升级内核！！"

- name: 校验节点系统架构
  assert:
    that: ansible_userspace_architecture == "x86_64"
    msg: "节点：{{ inventory_hostname }} 系统架构非64位，实际获取：{{ ansible_userspace_architecture }}，安装需求校验不通过。"

- name: 校验节点系统版本
  assert:
    that: ansible_distribution_version is version('7.4', '>=')
    msg: "节点：{{ inventory_hostname }} 系统版本期望不小于CentOS 7.4，实际获取：{{ ansible_distribution_version }}，安装需求校验不通过。"
  when:
    - ansible_distribution == "CentOS"

- name: 校验节点系统版本
  assert:
    that: ansible_distribution_version is version('7', '>=')
    msg: "节点：{{ inventory_hostname }} 系统版本期望不小于RedHat 7，实际获取：{{ ansible_distribution_version }}，安装需求校验不通过。"
  when:
    - ansible_distribution == "RedHat"

- name: 校验节点系统版本
  assert:
    that: ansible_distribution_version is version('16.04', '>=')
    msg: "Master节点：{{ inventory_hostname }} 系统版本期望不小于Ubuntu 16.04，实际获取：{{ ansible_distribution_version }}，安装需求校验不通过。"
  when:
    - ansible_distribution == "Ubuntu"

- name: 校验节点系统版本
  assert:
    that: ansible_distribution_version is version('9', '>=')
    msg: "Master节点：{{ inventory_hostname }} 系统版本期望不小于Debian 9，实际获取：{{ ansible_distribution_version }}，安装需求校验不通过。"
  when:
    - ansible_distribution == "Debian"

# 物理资源校验
- name: 校验 master 节点内存
  assert:
    that: ansible_memtotal_mb >= 2*1024*0.85
    msg: "Master节点：{{ inventory_hostname }} 内存期望不小于2G，实际获取：{{ ansible_memtotal_mb }}MB，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['masters'] + groups['add_masters'])

- name: 校验 worker 节点内存
  assert:
    that: ansible_memtotal_mb >= 4*1024*0.85
    msg: "Worker节点：{{ inventory_hostname }} 内存期望不小于4G，实际获取：{{ ansible_memtotal_mb }}MB，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['nodes'] + groups['add_nodes'])

- name: 校验 master 节点CPU核数
  assert:
    that: ansible_processor_vcpus >= 2
    msg: "Master节点：{{ inventory_hostname }} CPU核数期望不小于2C，实际获取：{{ ansible_memtotal_mb }}C，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['masters'] + groups['add_masters'])

- name: 校验 worker 节点CPU核数
  assert:
    that: ansible_processor_vcpus >= 2
    msg: "Worker节点：{{ inventory_hostname }} CPU核数期望不小于2C,实际获取：{{ ansible_memtotal_mb }}C，安装需求校验不通过。"
  when:
    - inventory_hostname in (groups['nodes'] + groups['add_nodes'])
