kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anonymous-proxy-role
rules:
  - apiGroups:
      - ""
    resources:
      - "services/proxy"
    resourceNames:
      - "https:kubernetes:"
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anonymous-proxy-binding
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-proxy-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:anonymous
