---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes:kubelet-config
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - kubelet-config
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes:kubelet-config
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes:kubelet-config
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:nodes
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:bootstrappers:kubernetes:default-node-token
