- block:
  - name: 创建下载二进制文件存放目录
    file: path="{{ cache_dir }}" state=directory

  - name: "判断 {{ item.value.file }} 文件是否存在"
    stat: path="{{ cache_dir + item.value.file }}"
    with_dict: "{{ binary }}"
    register: check_files

  - debug: msg="下载二进制文件包，根据网速不同，可能需要一定时间。。"
  - name: "下载 {{ item.value.file }} 二进制文件包"
    when:
      - item.item.value.enable == "true"
      - not item.stat.exists
    get_url:
      url: "{{ item.item.value.url }}"
      dest: "{{ cache_dir + item.item.value.file }}"
      validate_certs: False
    environment:
      http_proxy: "{{ proxy_env.http_proxy }}"
      https_proxy: "{{ proxy_env.https_proxy }}"
    with_items: "{{ check_files['results'] }}"
    register: download_files

  - name: "归档 {{ item.value.file }} 二进制文件"
    when:
      - out_item.item.value.enable == "true"
      - out_item.item.value.archive_dir is defined
    include_tasks: _binary.yml
    loop_control:
      loop_var: out_item
    with_items: "{{ check_files['results'] }}"
  run_once: true
  delegate_to: "{{ groups['deploy'][0] }}"
