- block:
  - name: 安装 rsync
    package: name=rsync state=present

  - name: 预装各组件
    when: "out_item.key == upgrade"
    include_tasks: "{{ inventory_dir }}/roles/prepare/preinstall/tasks/_preinstall.yml"
    loop_control:
      loop_var: out_item
    with_dict: "{{ binary }}"
  delegate_to: "{{ groups['deploy'][0] }}"
  run_once: true
  when: upgrade is defined and upgrade != ''

- block:
  - debug: msg="同步二进制文件到各节点，可能需要一定时间。。"
  - name: 从 deploy 节点分发各组件二进制文件至所有节点
    when:
      - item.key == upgrade
      - item.value.install_dir != ""
    copy:
      src: "{{ item.value.install_dir }}"
      dest: "{{ item.value.install_dir.split('/')[:-1]|join('/') }}"
      owner: root
      group: root
      mode: 0755
      remote_src: no
    with_dict: "{{ binary }}"
  when:
    - upgrade is defined and upgrade != ''
    - inventory_hostname != groups['deploy'][0]

- block:
  - debug: msg="同步镜像离线文件包到各节点，可能需要一定时间。。"
  - name: 从 deploy 节点分发镜像至所有节点
    when: item.key == image
    synchronize:
      src: "{{ cache_dir + 'images/' + item.value.file }}.tar"
      dest: "{{ cache_dir + 'images/' + item.value.file }}.tar"
    with_dict: "{{ images }}"
  when:
    - image is defined and image != ''
    - inventory_hostname != groups['deploy'][0]
