- block:
  - name: 渲染 etcd 配置文件
    template:
      src: "{{ inventory_dir }}/roles/etcd/templates/etcd-config.yml.j2"
      dest: "{{ etcd_config_dir }}/config.yml"

  - name: 配置 etcd.sh 到/etc/profile.d/
    template:
      src: "{{ inventory_dir }}/roles/etcd/templates/etcd.sh.j2"
      dest: "{{ profile_dir }}/etcd.sh"
      owner: root
      group: root
      mode: 0755

  - name: 配置 etcd 备份脚本
    template:
      src: "{{ inventory_dir }}/roles/etcd/templates/etcd_cron.sh.j2"
      dest: "{{ etcd_bin_dir }}/etcd_cron.sh"
      owner: root
      group: root
      mode: 0755

  - name: 启动服务，并设置开机启动
    when: inventory_hostname in (groups['kube_etcds'] | difference(groups['delete_etcds']) | difference(groups['add_etcds']) | unique)
    systemd:
      name: etcd
      daemon_reload: yes
      state: restarted
      enabled: yes
    register: started_etcd
    until: started_etcd is succeeded
    retries: 3
    delay: "{{ retry_stagger }}"

  - name: 以轮询的方式等待服务启动完成
    when: inventory_hostname in (groups['kube_etcds'] | difference(groups['delete_etcds']) | difference(groups['add_etcds']) | unique)
    shell: "systemctl status etcd.service | grep Active"
    register: etcd_status
    until: '"running" in etcd_status.stdout'
    retries: 2
    delay: "{{ retry_stagger }}"

  - name: 检查服务状态
    when: inventory_hostname in (groups['kube_etcds'] | difference(groups['delete_etcds']) | difference(groups['add_etcds']) | unique)
    uri:
      method: "GET"
      url: "https://{{ etcd_listen_addr }}:2379/health"
      validate_certs: no
      client_cert: "{{ etcd_cert_healthcheck_client }}"
      client_key: "{{ etcd_cert_healthcheck_client_key }}"
    register: result
    until: result.status is defined and result.status == 200
    retries: 3
    delay: "{{ retry_stagger }}"
  when: inventory_hostname in (groups['etcds'] | difference(groups['delete_etcds']) | unique)

- block:
  - name: 获取 etcd member 状态
    shell: >
      ETCDCTL_API=3 {{ etcd_bin_dir }}/etcdctl \
      --cert {{ etcd_cert_healthcheck_client }} \
      --key  {{ etcd_cert_healthcheck_client_key }} \
      --cacert {{ etcd_ca }} \
      --endpoints {{ etcd_servers }} \
      member list | grep {{ inventory_hostname }};
    register: get_etcd_member

  - name: 新节点 加入 etcd 集群中
    when: get_etcd_member.stdout == ''
    shell: >
      ETCDCTL_API=3 {{ etcd_bin_dir }}/etcdctl \
      --cert {{ etcd_cert_healthcheck_client }} \
      --key  {{ etcd_cert_healthcheck_client_key }} \
      --cacert {{ etcd_ca }} \
      --endpoints {{ etcd_servers }} \
      member add {{ hostvars[inventory_hostname].ansible_hostname }} --peer-urls={{ etcd_listen_peer_urls }}
  delegate_to: "{{ (groups['kube_etcds'] | difference(groups['delete_etcds']) | unique | first) }}"
  when: inventory_hostname in (groups['add_etcds'] | difference(groups['delete_etcds']) | unique )

- set_fact:
    etcd_initial_cluster_state: existing

- name: 新节点部署服务
  when:
    - "groups['add_etcds']|length > 0"
    - inventory_hostname in (groups['add_etcds'] | difference(groups['delete_etcds']) | unique )
  include_role:
    name: "{{ inventory_dir }}/roles/etcd"
