apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drain-node
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
      - list
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
