- name: 判断 cri-engine 是否安装(报错请忽略!!)
  shell: "{{ cri_engine_cli }} info >/dev/null 2>&1"
  environment:
    PATH: "{{ docker_bin_dir }}:{{ containerd_bin_dir }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin"
  register: check_cri_engine
  ignore_errors: true

- name: 拉取 containerd 二进制文件并安装
  when: out_item.key == "containerd"
  include_tasks: "{{ inventory_dir }}/roles/install-bin/tasks/_install.yml"
  loop_control:
    loop_var: out_item
  with_dict: "{{ binary }}"

- name: 拉取 docker 二进制文件并安装
  when:
    - out_item.key == "docker"
    - container_runtime == "docker"
  include_tasks: "{{ inventory_dir }}/roles/install-bin/tasks/_install.yml"
  loop_control:
    loop_var: out_item
  with_dict: "{{ binary }}"

- name: 安装 container runtime engine
  when: check_cri_engine.rc != 0
  include_role:
    name: container-runtime
    # tasks_from: container-runtime/tasks/main.yml
