- name: 获取 kubernetes master 节点相关证书
  slurp:
    src: "{{ item }}"
  with_items:
    - "{{ kubernetes_ca }}"
    - "{{ kubernetes_ca_key }}"
    - "{{ apiserver_cert }}"
    - "{{ apiserver_cert_key }}"
    - "{{ apiserver_kubelet_cert }}"
    - "{{ apiserver_kubelet_cert_key }}"
    - "{{ front_ca }}"
    - "{{ front_ca_key }}"
    - "{{ front_client }}"
    - "{{ front_client_key }}"
    - "{{ sa_public_key }}"
    - "{{ sa_private_key }}"
  register: slurp_kubernetes_master_certs
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: 分发 kubernetes master 相关证书到 master 节点
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ slurp_kubernetes_master_certs.results }}"
  when:
    - inventory_hostname != groups['masters'][0]
    - inventory_hostname in (groups['masters'] + groups['add-masters'])
