# 系统基础软件环境
- import_tasks: debian.yml
  when: 'ansible_distribution in ["Ubuntu","Debian"]'

- import_tasks: centos.yml
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'

# 公共系统参数设置
- import_tasks: common.yml
