- include_tasks: master.yml

- include_tasks: rbac/rbac.yml

- include_tasks: worker.yml

# - name: 等待 kubectl 能操作集群
#   shell: >
#     {{ kubernetes_bin_dir }}/kubectl get cs
#   environment:
#       KUBECONFIG: "{{ kubernetes_etc_dir }}/admin.conf"
#   until: waiting_for_cluster.rc == 0 and waiting_for_cluster.stdout.find("Unhealthy") == -1
#   retries: 3
#   delay: "{{ retry_stagger }}"
#   changed_when: false
#   register: waiting_for_cluster
