---
- name: 创建用户组
  group:
    name: "{{ user.group|default(user.name) }}"
    system: "{{ user.system|default(omit) }}"

- name: 创建用户
  user:
    comment: "{{ user.comment|default(omit) }}"
    createhome: "{{ user.createhome|default(omit) }}"
    group: "{{ user.group|default(user.name) }}"
    home: "{{ user.home|default(omit) }}"
    shell: "{{ user.shell|default(omit) }}"
    name: "{{ user.name }}"
    system: "{{ user.system|default(omit) }}"
