- block:
  - name: 生成 kubeadm token
    register: get_kubeadm_token
    shell: >
      if [ `{{ kubernetes_bin_dir }}/kubeadm token list | wc -l` -eq 0 ];then
        token=$({{ kubernetes_bin_dir }}/kubeadm token generate);
        {{ kubernetes_bin_dir }}/kubeadm token create ${token};
      else
        token=$({{ kubernetes_bin_dir }}/kubeadm token list | grep -v DESCRIPTION | awk -F' ' '{print $1}' | head -1)
        echo ${token}
      fi

  - set_fact:
      bootstrap_token: "{{ get_kubeadm_token.stdout }}"
  when: "enable_add_node | default(false)"
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: 所有 kube_cluster 节点渲染 kubeadm 的配置文件
  template:
    src: >-
      {% if inventory_hostname == groups['masters'][0] -%}
      kubeadm/kubeadm-controlplane-init.yaml.j2
      {%- elif inventory_hostname in groups['kube_masters'] -%}
      kubeadm/kubeadm-controlplane-join.yaml.j2
      {%- else -%}
      kubeadm/kubeadm-join.yaml.j2
      {%- endif %}
    dest: "{{ kubernetes_etc_dir }}/kubeadm-config.yaml"
    owner: "root"
    group: "root"
    mode: 0644

- name: 所有 kube_cluster 节点渲染相关配置文件
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { src: "kubelet/10-kubelet.conf", dest: "{{ systemd_service_dir }}/kubelet.service.d/10-kubeadm.conf" }
    - { src: "kubelet/kubelet.service", dest: "{{ systemd_service_dir }}/kubelet.service" }
    # - { src: "kubelet/kubelet.slice", dest: "{{ systemd_service_dir }}/kubelet.slice" }
    - { src: "kubelet/kubelet-config.yml", dest: "{{ kubelet_data_dir }}/config-tmp.yaml" }
    - { src: "kube-proxy/kube-proxy-config.yaml", dest: "{{ kube_proxy_data_dir }}/config-tmp.yaml" }
    # 不需要创建,static pod 会初始化失败
    # - { src: "cni-plugin/10-containerd-net.conflist", dest: "{{ cni_etc_dir }}/10-containerd-net.conflist" }

- name: 和并 kubelet-config.yml 和 kube-proxy-config.yaml 至 kubeadm-config.yaml
  shell: >
    cat {{ kubelet_data_dir }}/config-tmp.yaml >> {{ kubernetes_etc_dir }}/kubeadm-config.yaml;
    cat {{ kube_proxy_data_dir }}/config-tmp.yaml >> {{ kubernetes_etc_dir }}/kubeadm-config.yaml;
    # rm -f {{ kubelet_data_dir }}/config-tmp.yml;
    # rm -f {{ kube_proxy_data_dir }}/config-tmp.yml;

# - name: 所有 kube_cluster 节点加载 infra 和 kube-proxy 镜像
#   shell: "{{ docker_bin_dir }}/docker load -i {{ cache_dir + 'images/' + item }}.tar"
#   with_items:
#     - "{{ images.infra.file }}"
#     - "{{ images.proxy.file }}"

# - name: 加载 master 节点各组件镜像
#   when: "inventory_hostname in groups['kube_masters']"
#   shell: "{{ docker_bin_dir }}/docker load -i {{ cache_dir + 'images/' + item }}.tar"
#   with_items:
#     - "{{ images.apiserver.file }}"
#     - "{{ images.controller_manager.file }}"
#     - "{{ images.scheduler.file }}"

# - name: worker 节点加载 coredns 镜像
#   when: inventory_hostname in groups['kube_nodes']
#   shell: "{{ docker_bin_dir }}/docker load -i {{ cache_dir + 'images/' + item }}.tar"
#   with_items:
#     - "{{ images.coredns.file }}"
#     - "{{ images.autoscaler.file }}"

# https://github.com/kubernetes/kubernetes/issues/92175
# https://github.com/kubernetes/kops/issues/3223
# https://github.com/kubernetes/kubernetes/issues/43856
# https://phabricator.wikimedia.org/T219070
# - name: 启动 kubelet.slice
#   when: kubelet.kube_reserved_enabled is defined and  kubelet.kube_reserved_enabled
#   systemd:
#     name: "{{ item }}"
#     daemon_reload: yes
#     state: restarted
#     enabled: yes
#   with_items:
#     - kubelet.slice

- name: 设置 kubelet 开机启动
  systemd:
    name: kubelet
    daemon_reload: yes
    state: stopped
    enabled: yes

- include_tasks: master.yml

- include_tasks: worker.yml
