- name: 在 deploy 节点创建 {{ out_item.key }} 组件二进制文件预装目录
  when: out_item.value.install_dir != ""
  file: path="{{ out_item.value.install_dir }}" state=directory

- block:
  - name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
    when: out_item.key == "cfssl"
    copy:
      src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item + '_' +  cfssl_version + '_linux_amd64' }}"
      dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    with_items: "{{ out_item.value.bin }}"

  - name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
    when: out_item.key == "cfssljson"
    copy:
      src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item + '_' +  cfssl_version + '_linux_amd64' }}"
      dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    with_items: "{{ out_item.value.bin }}"

  - name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
    when: out_item.key == "cfssl_certinfo"
    copy:
      src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item + '_' +  cfssl_version + '_linux_amd64' }}"
      dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    with_items: "{{ out_item.value.bin }}"

  - name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
    when: out_item.key == "docker_compose"
    copy:
      src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item + '-' +  docker_compose_version }}"
      dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    with_items: "{{ out_item.value.bin }}"

  - name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
    when: out_item.key == "runc"
    copy:
      src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item + '.amd64-v' +  runc_version }}"
      dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    with_items: "{{ out_item.value.bin }}"

  - name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
    when: out_item.key == "helmfileargocd-linux-amd64-v1.8.1"
    copy:
      src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item + '_linux_amd64-v' +  helmfile_version }}"
      dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    with_items: "{{ out_item.value.bin }}"

  - name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
    when: out_item.key == "argocd"
    copy:
      src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item + '-linux-amd64-v' +  argocd_version }}"
      dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    with_items: "{{ out_item.value.bin }}"
  when: out_item.value.archive_dir == ""

- name: 在 deploy 节点预装 {{ out_item.key }} 组件二进制文件
  when: out_item.value.archive_dir != ""
  copy:
    src: "{{ cache_dir + out_item.value.archive_dir }}/{{ item }}"
    dest: "{{ out_item.value.install_dir }}/{{ item.split('/')[-1] }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  with_items: "{{ out_item.value.bin }}"
