# docker0 ip
bip: "192.168.100.1/24"
# 定义国内加速镜像地址
proxy_registries:
  - "https://8trm4p9x.mirror.aliyuncs.com"
  - "https://docker.mirrors.ustc.edu.cn"
  - "https://registry.docker-cn.com"
  - "http://010a79c4.m.daocloud.io"
  - "http://hub-mirror.c.163.com"
insecure_registries:
  - "{{ vip_address.split('.')[:-1] | join('.') }}.0/24"

# docker日志相关
log_driver: "json-file"
level: "warn"
maxsize: "10m"
maxfile: 3
# 开启 docker daemon iptables 规则，如果要使用 docker 创建容器设置为 true
enable_dockerd_iptables: true
# 开启 Restful API
enable_remote_api: false
