- name: 确认 etcd 运行状态
  command: /bin/true
  notify:
    - 启动服务，并设置开机启动
    - 以轮询的方式等待服务启动完成
    - 检查服务状态

- name: 启动服务，并设置开机启动
  systemd:
    name: etcd
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_etcd
  until: started_etcd is succeeded
  retries: 3
  delay: "{{ retry_stagger }}"

- name: 以轮询的方式等待服务启动完成
  when: started_etcd is succeeded
  shell: "systemctl status etcd.service | grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 2
  delay: "{{ retry_stagger }}"

- name: 检查服务状态
  uri:
    method: "GET"
    url: "https://{{ etcd_listen_addr }}:2379/health"
    validate_certs: no
    client_cert: "{{ etcd_cert_healthcheck_client }}"
    client_key: "{{ etcd_cert_healthcheck_client_key }}"
  register: result
  until: result.status is defined and result.status == 200
  retries: 5
  delay: "{{ retry_stagger }}"
