- name: 判断 python3 是否安装(报错请忽略!!)
  shell: >
    command -v python3 >/dev/null 2>&1
  register: python3_result
  ignore_errors: true

- name: 判断 pip3 是否安装(报错请忽略!!)
  shell: "command -v pip3 >/dev/null 2>&1"
  register: pip3_result
  ignore_errors: true

- name: 创建下载文件临时目录
  file:
    path: "{{ cache_dir }}"
    state: directory

- name: 安装 python3
  when: python3_result is failed
  include_tasks: "install.yml"

- name: 配置 pip3
  when: pip3_result is failed
  include_tasks: "pip.yml"

- name: 添加 pyenv 环境变量
  lineinfile:
    dest: "{{ python3_bashrc }}"
    state: present
    regexp: "pyenv"
    line: |
      export PATH="{{ ansible_user_dir }}/.pyenv/bin:{{ ansible_user_dir }}/.pyenv/shims:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
